on: push

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.publish.yml
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: parisk
            password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker compose alpha publish ghcr.io/parisk/docker-remote-include-test

  config:
    needs: publish
    runs-on: ubuntu-latest
    env:
      COMPOSE_EXPERIMENTAL_OCI_REMOTE: "1"
    steps:
      - uses: actions/checkout@v4
      - run: docker info
      - run: docker compose version
      - run: docker compose config --no-normalize
      - run: docker compose alpha viz --image --indentation-size=4 --networks --ports --spaces
