on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.publish.yml
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: parisk
            password: ${{ secrets.GHCR_PAT }}
      - run: docker compose alpha publish ghcr.io/parisk/docker-remote-include-test

  config:
    needs: publish
    runs-on: ubuntu-latest
    env:
      COMPOSE_EXPERIMENTAL_OCI_REMOTE: true
    steps:
      - uses: actions/checkout@v4
      - run: docker compose version
      - run: docker compose config --no-normalize
    